# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo_id',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojoApp.Dojo'),
        ),
    ]
