# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoApp', '0003_auto_20170714_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojoApp.Dojo'),
        ),
    ]
